### ISSUE TITLE
given Index.html is working only on Mozilla Firefox 

### ISSUE THREAD

**Issue by anandreddyks** [vchatterji/opml2json#3]
If i open in chrome or safari, I can see empty page. What could be the issue ?

**Comment by vchatterji** [comment]
You need to put the files on a webserver. The D3.js library is trying to make a XMLHttpRequest to load the JSON. The XMLHttpRequest is not supported in Chrome over the file:// protocol.

You can see the error in the Javascript console.

If you put them on a server (for example using Express), it should load fine in the browser when accessed using http://
